/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 02-Nov-2017 2:30:50 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `currencies` CASCADE
;

DROP TABLE IF EXISTS `date` CASCADE
;

DROP TABLE IF EXISTS `m2m_date_currencies` CASCADE
;

/* Create Tables */

CREATE TABLE `currencies`
(
	`c_id` INT NOT NULL AUTO_INCREMENT,
	`c_name` VARCHAR(3) NOT NULL,
	CONSTRAINT `PK_currencies` PRIMARY KEY (`c_id` ASC)
)

;

CREATE TABLE `date`
(
	`d_id` INT NOT NULL AUTO_INCREMENT,
	`d_date` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_date` PRIMARY KEY (`d_id` ASC)
)

;

CREATE TABLE `m2m_date_currencies`
(
	`dc_id` INT NOT NULL AUTO_INCREMENT,
	`d_id` INT NOT NULL,
	`c_id` INT NOT NULL,
	`dc_value` FLOAT(12,4) NOT NULL,
	`dc_scale` INT NOT NULL DEFAULT 1,
	CONSTRAINT `PK_m2m_date_currencies` PRIMARY KEY (`dc_id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `currencies` 
 ADD CONSTRAINT `UNQ_c_name` UNIQUE (`c_name` ASC)
;

ALTER TABLE `date` 
 ADD CONSTRAINT `UNQ_d_date` UNIQUE (`d_date` ASC)
;

ALTER TABLE `m2m_date_currencies` 
 ADD INDEX `IXFK_m2m_date_currencies_currencies` (`c_id` ASC)
;

ALTER TABLE `m2m_date_currencies` 
 ADD INDEX `IXFK_m2m_date_currencies_date` (`d_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `m2m_date_currencies` 
 ADD CONSTRAINT `FK_m2m_date_currencies_currencies`
	FOREIGN KEY (`c_id`) REFERENCES `currencies` (`c_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `m2m_date_currencies` 
 ADD CONSTRAINT `FK_m2m_date_currencies_date`
	FOREIGN KEY (`d_id`) REFERENCES `date` (`d_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
